version: '3.9'

services:

  db:
    image: postgres:latest
    container_name: carrito_conteiner
    restart: always
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - POSTGRES_DB=carrito_db
      - POSTGRES_USER=richard
      - POSTGRES_PASSWORD=12345678
    ports:
      - "5432:5432"
